/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parkrdu;

import java.io.FileFilter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.Locale;
import java.util.Properties;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.AbstractButton;

import java.util.Date;
import java.util.Enumeration;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.SpinnerNumberModel;
import javax.swing.JFormattedTextField;


/**
 *
 * @author DavisT
 */
public class TestParameters extends javax.swing.JFrame {
    
    public Properties testdata;
    public String screenshotName = "screenshot"; // screenshot filename
    public String screenshotDir = ""; // screenshot directory


    /**
     * Creates new form TestParameters
     */
    public TestParameters() {
        initComponents();
        testdata = new Properties();
    }
   
    /**
     * 
     * @param testdata 
     */
    public TestParameters(Properties testdata){
       initComponents(); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ccType_buttongrp = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        zipCode_text = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        emailAddress_text = new javax.swing.JTextField();
        lastName_text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        firstName_text = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setToolTipText("Enter testing credit card information");
        ccName_text = new javax.swing.JTextField();
        ccNumber_text = new javax.swing.JTextField();
        visa_button = new javax.swing.JRadioButton();
        mastercard_button = new javax.swing.JRadioButton();
        discover_button = new javax.swing.JRadioButton();
        amex_button = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        expireYear_text = new javax.swing.JTextField();
        expireMonth_text = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ccCSV_text = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        entryDate_text = new javax.swing.JFormattedTextField();
        entryTime_text = new javax.swing.JFormattedTextField();
        exitDate_text = new javax.swing.JFormattedTextField();
        exitTime_text = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        runsCount_spin = new javax.swing.JSpinner();
        runsCount_spin.setModel(new SpinnerNumberModel(new Integer(1), null, null, new Integer(1)));
        jLabel11 = new javax.swing.JLabel();
        incDate_check = new javax.swing.JCheckBox();
        incDateCount_spin = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        checkLinksTest_check = new javax.swing.JCheckBox();
        checkLinksTest_check.setSelected(true);
        createBooking_check = new javax.swing.JCheckBox();
        createBookingAccount_check = new javax.swing.JCheckBox();
        reminderAccount_check = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        file_menu = new javax.swing.JMenu();
        saveParms_menuItem = new javax.swing.JMenuItem();
        saveParmsAs = new javax.swing.JMenuItem();
        loadParms_menuItem = new javax.swing.JMenuItem();
        exit_menuItem = new javax.swing.JMenuItem();
        edit_menu = new javax.swing.JMenu();
        runTest_menu = new javax.swing.JMenu();
        execute_menuItem = new javax.swing.JMenuItem();

        jDialog1.setIconImage(null);
        jDialog1.setModal(true);
        jDialog1.setName("confirm exit"); // NOI18N
        jDialog1.setResizable(false);
        jDialog1.setType(java.awt.Window.Type.POPUP);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ParkRDU");

        try {
            zipCode_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Zip code");

        jLabel3.setText("Email address");

        emailAddress_text.setText("some@email.com");

        lastName_text.setText("Test");

        jLabel2.setText("Last Name");

        jLabel1.setText("First Name");

        firstName_text.setText("Tester");
        
        JLabel lblNewLabel = new JLabel("Password");
        
        password_text = new JTextField();
        password_text.setColumns(10);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
        							.addPreferredGap(ComponentPlacement.UNRELATED))
        						.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
        						.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
        						.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(firstName_text, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addContainerGap())
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        								.addComponent(lastName_text, Alignment.LEADING)
        								.addComponent(password_text, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(zipCode_text, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        								.addComponent(emailAddress_text, Alignment.LEADING, 190, 190, Short.MAX_VALUE))
        							.addGap(168))))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(lblNewLabel)
        					.addContainerGap(571, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel1)
        				.addComponent(firstName_text, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(lastName_text, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(9)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3)
        				.addComponent(emailAddress_text, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(7)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblNewLabel)
        				.addComponent(password_text, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel4)
        				.addComponent(zipCode_text, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        jTabbedPane1.addTab("Basic Info", jPanel1);

        ccName_text.setText("Tester test");

        ccNumber_text.setText("4444333322221111");

        ccType_buttongrp.add(visa_button);
        visa_button.setText("Visa");

        ccType_buttongrp.add(mastercard_button);
        mastercard_button.setText("Mastercard");

        ccType_buttongrp.add(discover_button);
        discover_button.setText("Discover");

        ccType_buttongrp.add(amex_button);
        amex_button.setText("American Express");

        jLabel5.setText("Name");

        jLabel6.setText("Number");

        expireYear_text.setText("Year");

        expireMonth_text.setText("Month");

        jLabel7.setText("Expiration");

        jLabel8.setText("/");

        jLabel15.setText("CSV number");

        ccCSV_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ccCSV_text.setText("123");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amex_button)
                            .addComponent(discover_button)
                            .addComponent(mastercard_button)
                            .addComponent(visa_button)
                            .addComponent(ccName_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ccNumber_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ccCSV_text, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(expireMonth_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(expireYear_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccName_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccNumber_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel15)
                    .addComponent(ccCSV_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(visa_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mastercard_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(discover_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amex_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expireYear_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expireMonth_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Credit card", jPanel2);

        jLabel9.setText("Exit Date");

        jLabel10.setText("Entry Date");

        jLabel13.setText("Exit Time");

        jLabel14.setText("Entry Time");

        entryDate_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        entryDate_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryDate_textActionPerformed(evt);
            }
        });


        entryTime_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.SimpleDateFormat.SHORT))));
        exitDate_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));

        exitTime_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel10)
        				.addComponent(jLabel14))
        			.addGap(3)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(entryTime_text, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jLabel13))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(entryDate_text, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jLabel9)))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(exitTime_text)
        				.addComponent(exitDate_text, GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
        			.addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGap(31)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel10)
        				.addComponent(jLabel9)
        				.addComponent(entryDate_text, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(exitDate_text, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel13)
        				.addComponent(jLabel14)
        				.addComponent(entryTime_text, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(exitTime_text, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel3.setLayout(jPanel3Layout);

        jTabbedPane1.addTab("Dates", jPanel3);

        jLabel11.setText("No. of runs");

        incDate_check.setText("Increment date");

        incDateCount_spin.setModel(new javax.swing.SpinnerNumberModel(1, null, 10, 1));

        jLabel12.setText("Select a browser");

        jLabel16.setText("Tests to run");

        checkLinksTest_check.setText("Check links");
        createBooking_check.setText("Create booking");

        createBookingAccount_check.setText("Create booking w/account");

        reminderAccount_check.setText("Send reminder");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reminderAccount_check)
                    .addComponent(createBookingAccount_check)
                    .addComponent(createBooking_check)
                    .addComponent(checkLinksTest_check)
                    .addComponent(jLabel16))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkLinksTest_check)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createBooking_check)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createBookingAccount_check)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reminderAccount_check)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        browser_list = new javax.swing.JList<>();
        
                browser_list.setModel(new javax.swing.AbstractListModel<String>() {
                    String[] strings = { "Firefox", "Chrome", "Internet Explorer 11", "Opera", "Edge" };
                    public int getSize() { return strings.length; }
                    public String getElementAt(int i) { return strings[i]; }
                });
                browser_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                browser_list.setSelectedIndex(0);
        
        JLabel lblScreenshotName = new JLabel("Screenshot name");
        
        screenshotName_text = new JTextField();
        screenshotName_text.setColumns(10);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4Layout.setHorizontalGroup(
        	jPanel4Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel4Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, 187, GroupLayout.PREFERRED_SIZE)
        			.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel12)
        					.addGap(172)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addComponent(browser_list, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel4Layout.createSequentialGroup()
        							.addComponent(jLabel11)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(runsCount_spin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel4Layout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblScreenshotName)))
        					.addGap(18)
        					.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(screenshotName_text, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addGroup(jPanel4Layout.createSequentialGroup()
        							.addComponent(incDate_check)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(incDateCount_spin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))))
        			.addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
        	jPanel4Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel4Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel4Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(runsCount_spin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel11)
        						.addComponent(incDate_check)
        						.addComponent(incDateCount_spin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lblScreenshotName)
        						.addComponent(screenshotName_text, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
        					.addGroup(jPanel4Layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(jPanel4Layout.createSequentialGroup()
        							.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
        							.addGap(53))
        						.addGroup(jPanel4Layout.createSequentialGroup()
        							.addComponent(jLabel12)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(browser_list, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
        							.addGap(27)))))
        			.addContainerGap())
        );
        jPanel4.setLayout(jPanel4Layout);

        jTabbedPane1.addTab("Test cond.", jPanel4);

        file_menu.setText("File");
        file_menu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                file_menuMenuSelected(evt);
            }
        });

        saveParms_menuItem.setText("Save parameters");
        saveParms_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveParms_menuItemActionPerformed(evt);
            }
        });
        file_menu.add(saveParms_menuItem);

        saveParmsAs.setText("Save as...");
        saveParmsAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveParmsAsActionPerformed(evt);
            }
        });
        file_menu.add(saveParmsAs);

        loadParms_menuItem.setText("Load Test Parameters");
        loadParms_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadParms_menuItemActionPerformed(evt);
            }
        });
        file_menu.add(loadParms_menuItem);

        exit_menuItem.setText("Exit");
        exit_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_menuItemActionPerformed(evt);
            }
        });
        file_menu.add(exit_menuItem);

        jMenuBar1.add(file_menu);

        edit_menu.setText("Edit");
        jMenuBar1.add(edit_menu);

        runTest_menu.setText("Run test");
        runTest_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runTest_menuActionPerformed(evt);
            }
        });

        execute_menuItem.setText("Execute");
        execute_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                execute_menuItemActionPerformed(evt);
            }
        });
        
        ScreenshotLocation_menu = new JMenuItem("Screenshot location");
        ScreenshotLocation_menu.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
        		ScreenshotLocation_menuItemActionPerformed(evt);
        	}


        });
        runTest_menu.add(ScreenshotLocation_menu);
        runTest_menu.add(execute_menuItem);

        jMenuBar1.add(runTest_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadParms_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadParms_menuItemActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Test data","td");
        jFileChooser1.setFileFilter(filter);
        jFileChooser1.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int returnVal = jFileChooser1.showOpenDialog(rootPane);
        if (returnVal ==JFileChooser.APPROVE_OPTION){
            try {
            // TODO add your handling code here:
            // save test data
            FileInputStream in = new FileInputStream(jFileChooser1.getSelectedFile());
            testdata.load(in);
            in.close();
            
            } catch (IOException ex) {
                Logger.getLogger(TestParameters.class.getName()).log(Level.SEVERE, null, ex);
            }
            update_gui();
        }
    }//GEN-LAST:event_loadParms_menuItemActionPerformed

    private void update_gui() {
    // update the gui with loaded test data
    ccCSV_text.setText(testdata.getProperty("ccCSV"));
    ccName_text.setText(testdata.getProperty("ccName"));
    ccNumber_text.setText(testdata.getProperty("ccNumber"));
    emailAddress_text.setText(testdata.getProperty("email"));
    entryDate_text.setText(testdata.getProperty("entrydate"));
    exitDate_text.setText(testdata.getProperty("exitdate"));
    //entryTime_text.setText(testdata.getProperty("entrytime"));
    //exitTime_text.setText(testdata.getProperty("exittime"));
    expireYear_text.setText(testdata.getProperty("ccyear"));
    expireMonth_text.setText(testdata.getProperty("ccmonth"));
    firstName_text.setText(testdata.getProperty("firstname"));
    lastName_text.setText(testdata.getProperty("lastname"));
    zipCode_text.setText(testdata.getProperty("zipcode"));
    
    incDateCount_spin.setValue(Integer.parseInt(testdata.getProperty("incdatevalue")));
    runsCount_spin.setValue(Integer.parseInt(testdata.getProperty("runscount")));
    screenshotName_text.setText(screenshotName);
    
	String entryTime;
	String exitTime;
	
	SimpleDateFormat time24hour = new SimpleDateFormat("HH:mm"); 
	try {
		
		entryTime = time24hour.parse(testdata.getProperty("entrytime")).toString();
		exitTime = time24hour.parse(testdata.getProperty("exittime")).toString();
		entryTime_text.setText(entryTime);
		exitTime_text.setText(exitTime);
	} catch (ParseException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
    
    }
    
    private void file_menuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_file_menuMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_file_menuMenuSelected

    private void exit_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_menuItemActionPerformed
        // TODO add your handling code here:
        //show alert about not saving
        int returnVal = JOptionPane.showConfirmDialog(rootPane, "Exit application\n Unsaved data will be lost");
        if (returnVal == JOptionPane.OK_OPTION){
            System.exit(0);
        };
        
    }//GEN-LAST:event_exit_menuItemActionPerformed

    private void entryDate_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryDate_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryDate_textActionPerformed

    private void runTest_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runTest_menuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_runTest_menuActionPerformed

    private void saveParms_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveParms_menuItemActionPerformed
        try {
            // TODO add your handling code here:
            // save test data
            FileOutputStream out = new FileOutputStream("ParkRDU.td");
            update_testdata();
            testdata.store(out, "Park RDU save test data");
            out.close();
        } catch (IOException ex) {
            Logger.getLogger(TestParameters.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        
    }//GEN-LAST:event_saveParms_menuItemActionPerformed

    private void execute_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_execute_menuItemActionPerformed
        // TODO add your handling code here:
    	Integer loops = Integer.parseInt(runsCount_spin.getValue().toString());
        update_testdata();
        
        while (loops > 0){
	        if (checkLinksTest_check.isSelected()){
	            CheckLinks linkTest = new CheckLinks(testdata, browser_list.getSelectedValue());
	            try{
	                //linkTest.setUp(browser_list.getSelectedValue());
	                linkTest.testCheckLinks();
	            }catch (Exception ex){
	                Logger.getLogger(TestParameters.class.getName()).log(Level.SEVERE, null, ex);
	            }
	        }
	        if (createBooking_check.isSelected()){
	            Book bookTest = new Book(testdata, browser_list.getSelectedValue());
	        //System.console().writer().println("starting booking test");
	
	            try{
	                bookTest.testBook();
	            } catch (Exception ex) {
	                Logger.getLogger(TestParameters.class.getName()).log(Level.SEVERE, null, ex);
	            }
	        }
	        if (createBookingAccount_check.isSelected()){
	            Book bookTest = new Book(testdata, emailAddress_text.getText(), password_text.getText() , browser_list.getSelectedValue());
	            try {
	                bookTest.testBook();
	            } catch (Exception ex){
	                Logger.getLogger(TestParameters.class.getName()).log(Level.SEVERE, null, ex);
	            }
	        }
	        loops--;
        }
    }//GEN-LAST:event_execute_menuItemActionPerformed

	private void ScreenshotLocation_menuItemActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
		jFileChooser1.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = jFileChooser1.showOpenDialog(rootPane);
        if (returnVal ==JFileChooser.APPROVE_OPTION){
        	//screenshotName = jFileChooser1.getSelectedFile().getName();
        	screenshotDir = jFileChooser1.getSelectedFile().getPath();
        }
        update_testdata();
	}    
    private void saveParmsAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveParmsAsActionPerformed
        String comments;
        update_testdata();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Test data","td");
        jFileChooser1.setFileFilter(filter);
        jFileChooser1.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int returnVal = jFileChooser1.showOpenDialog(rootPane);
        if (returnVal ==JFileChooser.APPROVE_OPTION){
            try {
            // TODO add your handling code here:
            // save test data
            // ask for a comment
            comments=JOptionPane.showInputDialog("Type a comment");
            FileOutputStream out = new FileOutputStream(jFileChooser1.getSelectedFile());
            testdata.store(out, comments);
            out.close();
            } catch (IOException ex) {
                Logger.getLogger(TestParameters.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_saveParmsAsActionPerformed

    public String get_entryDate_text(){
        return entryDate_text.getText();
    };
    
    public void update_testdata(){
    	String entryTime;
    	String exitTime;
    	
    	SimpleDateFormat time24hour = new SimpleDateFormat("HH:mm"); 
    	try {
			entryTime = time24hour.parse(entryTime_text.getText()).toString();
			testdata.put("entrytime", entryTime);
			exitTime = time24hour.parse(exitTime_text.getText()).toString();
			testdata.put("exittime", exitTime);
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
        testdata.put("ccCSV", ccCSV_text.getText());
        testdata.put("ccName", ccName_text.getText());
        testdata.put("ccNumber", ccNumber_text.getText());
        //testdata.setProperty("ccType", cctype);
        testdata.put("email", emailAddress_text.getText());
        testdata.put("entrydate",entryDate_text.getText());
        testdata.put("exitdate",exitDate_text.getText());
        testdata.put("ccyear",expireYear_text.getText());
        testdata.put("ccmonth",expireMonth_text.getText());
        testdata.put("firstname", firstName_text.getText());
        testdata.put("lastname", lastName_text.getText());
        testdata.put("zipcode", zipCode_text.getText().toString());
        testdata.put("runscount", runsCount_spin.getValue().toString());
        testdata.put("screenshotname", screenshotName_text.getText());
        testdata.put("screenshotdir", screenshotDir);
        
        //testdata.setProperty("incdatevalue", incDate_check.isSelected());
        if (incDate_check.isSelected()){
            testdata.put("incdatevalue",incDateCount_spin.getValue().toString());
        }else{
            testdata.put("incdatevalue","1");
        }
        
        //check which credit card type
        //cctyperadio = ccType_buttongrp.getElements();
        for(Enumeration<AbstractButton> cctypebuttons = ccType_buttongrp.getElements(); cctypebuttons.hasMoreElements();){
            AbstractButton cctype = cctypebuttons.nextElement();
            if (cctype.isSelected()){
                testdata.put("cctype",cctype.getText());
                
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestParameters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify  
    //[start] donotmodify
    private javax.swing.JRadioButton amex_button;
    private javax.swing.JList<String> browser_list;
    private javax.swing.JFormattedTextField ccCSV_text;
    private javax.swing.JTextField ccName_text;
    private javax.swing.JTextField ccNumber_text;
    private javax.swing.ButtonGroup ccType_buttongrp;
    private javax.swing.JCheckBox checkLinksTest_check;
    private javax.swing.JCheckBox createBookingAccount_check;
    private javax.swing.JCheckBox createBooking_check;
    private javax.swing.JRadioButton discover_button;
    private javax.swing.JMenu edit_menu;
    private javax.swing.JTextField emailAddress_text;
    private javax.swing.JFormattedTextField entryDate_text;
    private javax.swing.JFormattedTextField entryTime_text;
    private javax.swing.JMenuItem execute_menuItem;
    private javax.swing.JFormattedTextField exitDate_text;
    private javax.swing.JFormattedTextField exitTime_text;
    private javax.swing.JMenuItem exit_menuItem;
    private javax.swing.JTextField expireMonth_text;
    private javax.swing.JTextField expireYear_text;
    private javax.swing.JMenu file_menu;
    private javax.swing.JTextField firstName_text;
    private javax.swing.JSpinner incDateCount_spin;
    private javax.swing.JCheckBox incDate_check;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lastName_text;
    private javax.swing.JMenuItem loadParms_menuItem;
    private javax.swing.JRadioButton mastercard_button;
    private javax.swing.JCheckBox reminderAccount_check;
    private javax.swing.JMenu runTest_menu;
    private javax.swing.JSpinner runsCount_spin;
    private javax.swing.JMenuItem saveParmsAs;
    private javax.swing.JMenuItem saveParms_menuItem;
    private javax.swing.JRadioButton visa_button;
    private javax.swing.JFormattedTextField zipCode_text;
    private JTextField password_text;
    private JMenuItem ScreenshotLocation_menu;
    private JTextField screenshotName_text;
}
